"""Initial migration after reset

Revision ID: 1c020bd155a5
Revises: 
Create Date: 2025-04-28 23:09:13.211134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c020bd155a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('CONTRIBUTION', 'WITHDRAWAL_REQUEST', 'WITHDRAWAL_APPROVED', 'WITHDRAWAL_REJECTED', name='notificationtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('notifications_sender_id_fkey', type_='foreignkey')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('reference_amount')
        batch_op.drop_column('emailed')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emailed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('notifications_sender_id_fkey', 'users', ['sender_id'], ['id'])
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CONTRIBUTION', 'WITHDRAWAL_REQUEST', 'WITHDRAWAL_APPROVED', 'WITHDRAWAL_REJECTED', name='notificationtype'),
               existing_nullable=False)

    # ### end Alembic commands ###
