"""Reconcile transactiontype ENUM

Revision ID: 67445adeb3c2
Revises: ba007040d77d
Create Date: 2025-03-30 01:05:35.722639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67445adeb3c2'
down_revision = 'ba007040d77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.Enum('CONTRIBUTION', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('member', 'GROUP_ADMIN', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'member'::userrole"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('member', 'GROUP_ADMIN', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'member'::userrole"))

    op.drop_table('transactions')
    # ### end Alembic commands ###
