"""Mpesa dajara API 

Revision ID: c6de5f0b53d1
Revises: 1f2d9cad86d1
Create Date: 2025-04-10 11:22:56.642421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6de5f0b53d1'
down_revision = '1f2d9cad86d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_request_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_confirmation_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('reference')
        batch_op.drop_column('mpesa_confirmation_code')
        batch_op.drop_column('mpesa_request_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
