"""WITHDRAWAL REJECT

Revision ID: fc8735746174
Revises: c6de5f0b53d1
Create Date: 2025-04-11 10:25:19.225025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8735746174'
down_revision = 'c6de5f0b53d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('reference_amount')

    # ### end Alembic commands ###
